<!DOCTYPE html>
 <html>
 <head>
     <meta charset="utf-8"/>
     <title>${project} Application</title>
 </head>
   <body>
      <h1 class="title">Welcome to <code>${project}</code>, an
       application generated by the <a
       href="http://docs.pylonsproject.org/projects/pyramid/dev/"
      >pyramid</a> web application framework.</h1>
   </body>
 </html>